### PR TITLE
Add ExtremeStats.jl

### PR DESCRIPTION
**Pull request by juliohm**
Extreme value statistics category.

### CODE REVIEW

**Comment by juliohm** [comment]
@svaksha I noticed that ExtremeStats.jl was added to the probabilistic programming category without notice, could you please explain? I don't see how the package fits in that category and I appreciate if you could notify next time when changes are made before merges. I submitted the package on its own category, but would be happy to iterate with you an appropriate location.

**Comment by svaksha** [comment]
hi @juliohm, your package was already added by me on 28feb in this commit (https://github.com/svaksha/Julia.jl/commit/e761f3451734817e391dd3e2312e0f03f9e9f1d2#diff-6ebf7c4a0aae1a2beb594b27ec6278c8) but I didnt realise this before I merged your commit. My bad, hope that explains?

**Comment by svaksha** [comment]
btw, if the category isnt appropriate, feel free to point me to a category - I generally use WP cats for easier reference points.

**Comment by juliohm** [comment]
Thank you @svaksha, I think I understand what happened, but why the changes in this PR are not visible in the latest Statistics.md? I would just delete the entry in the probabilistic programming category and apply the changes in this PR. Makes sense?

**Comment by svaksha** [comment]
Does your package not fit in the "probabilistic programming" cat? Generally speaking, I try to keep the categories broad - read, if there is more than one package it gets its own cat tag so if you can point me to the WP category for your package (and any others in this repo that are wrongly categorised or fall within the new cat), I will be happy to reorder it. HTH.

**Comment by juliohm** [comment]
Extreme value statistics is not related to probability nor to programming.
Another category would be more appropriate, I will search for another
category already in the repo.

**Pull request merged**
