### PR TITLE
Add FStrings.jl

### PR DESCRIPTION
**Pull request by magonser**
Added [`FStrings.jl`](https://github.com/magonser/FStrings.jl)

### CODE REVIEW

**Comment by magonser** [comment]
Should I have modified the respective Markdown file as well?

**Comment by svaksha** [comment]
Hi, sorry I missed this notification. 
Yes, add the package info in the relevant section in the markdown file, then run the scrape script and commit locally, remote, and add to this PR. Thanks

**Comment by magonser** [comment]
Hi @svaksha ,

thanks for your answer and no problem. After syncing the latest changing from your repo, I have updated the information in `API.md` and run `src/scrape.jl`. However looking at the current diff of this PR, it seems that the `db.csv` has also been updated w.r.t. some other packages. Is this a problem? I could remove the relevant entries manually...

**Comment by svaksha** [comment]
Hi,

On Sat, Apr 25, 2020 at 8:57 AM Markus Gonser <notifications@github.com> wrote:
>
> Hi @svaksha ,
>
> thanks for your answer and no problem. After syncing the latest changing from your repo, I have updated the information in API.md and run src/scrape.jl. However looking at the current diff of this PR, it seems that the db.csv has also been updated w.r.t. some other packages. Is this a problem? I could remove the relevant entries manually...
>
>

Thanks. The `db.csv` has never been edited manually so please only use
the scrape script to regenerate the file always.

Alternatively, if you have edited it manually, please delete and 'git
pull' (after you stash uncommitted local changes) which will update
your local git repo. Then run script & commit local changes and push
to your git fork (at this point it may ask for a merge from remote),
then a PR. But its better to avoid manually editing the csv file.

Hope that helps!

॥ SVAKSHA ॥ स्वक्ष ॥ BIO: http://svaksha.com/pages/BIO ॥ PUB:
http://svaksha.com/pages/PUB ॥ Git:: https://github.com/svaksha,
https://gitlab.com/svaksha ॥ T:: https://twitter.com/svaksha ॥

**Comment by magonser** [comment]
Ok - thank you for the explanation. I see that you have merged it - thank you for your support again!

**Pull request merged**
