### PR TITLE
Repo renamed similar to other packages.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Moved to: [HydrocarbonNets.jl](https://github.com/Ismael-VC/HydrocarbonNets.jl)

### CODE REVIEW

**Comment by svaksha** [comment]
Hi, Merged it. 
Also do update the repo fork to reflect hte name change to Julia.jl last year. Thanks.

**Comment by svaksha** [comment]
BTW, lest it confuses people, you might want to make it clear in the `AHN.jl` repo that people should use `HydrocarbonNets.jl`. Thanks

**Comment by Ismael-VC** [comment]
Thank you very much!

Yes I've updated [`Ismael-VC/AHN.jl/README.md`](https://github.com/Ismael-VC/AHN.jl/blob/master/README.md) to clearly point anyone to [`HydrocarbonNets.jl`](https://github.com/Ismael-VC/HydrocarbonNets.jl).

**Comment by svaksha** [comment]
Since you mentioned that you were new to git, just wanted to let you know that git (and github) allows you to rename a repo without losing the commit history. For this you would have to do two things:
1. In the local repo, rename the toplevel directory `AHN.jl` to `HydrocarbonNets.jl`, edit the `config` file within the .git directory to reflect this change, and then
2. In github, visit the "settings" link and rename your package, which changes the clone command.

The above should allow you to preserve the commit history. Hope that helps, @svaksha

**Pull request merged**
