### PR TITLE
[Added] BioJulia : A bioinformatics infrastructure for the julia language

### PR DESCRIPTION
**Pull request by Sov-trotter**
Biojulia is a popular set of tools for Bioinformatics.

### CODE REVIEW

**Comment by Sov-trotter** [comment]
Didn't mean to delete the branch. Apologies.

**Comment by Sov-trotter** [comment]
I was initially trying to do it. But BioJulia  has around 50+ different packages and and such assortment is not just time-consuming but also subjective to misinterpretations.

**Comment by Sov-trotter** [comment]
I'll see if I can categorize most of the packages.

**Comment by svaksha** [comment]
Hi, its been a few months since the change request. Do you still want to merge the changed files or can I close the PR? 

You can always open a fresh PR - a better option as there have been other merges meanwhile.

**Comment by Sov-trotter** [comment]
Oh. It had completely skipped me. I'll make the fresh PR.  :)

**Comment by svaksha** [comment]
Cool, closing this & look forward to the new PR.

**Pull request closed without merging**
