### PR TITLE
Update FileIO.md

### PR DESCRIPTION
**Pull request by strickek**
Insert my julia package `ReadWriteDlm2` to FileIO/Data Formats/Tabular Data Matrix

### CODE REVIEW

**Comment by strickek** [comment]
Any problem with adding ReadWritDlm2 to IO?

**Comment by svaksha** [comment]
@strickek, tried to manually fix it but git rejected it. Could you do a fresh clone and file a new PR please?

**Comment by svaksha** [comment]
@strickek , fixed it in this commit: https://github.com/svaksha/Julia.jl/commit/46b51667ea9ca82acdde984902fb12e68c606977#diff-3c8965125a574bc422b4006cddc6505e

**Comment by strickek** [comment]
Thank you!

SVAKSHA <notifications@github.com> schrieb am So., 30. Sep. 2018, 11:43:

**Pull request closed without merging**
