### PR TITLE
Added Kate Notepad and update Juno's link

### PR DESCRIPTION
**Pull request by melvin0008**

### CODE REVIEW

**Comment by svaksha** [comment]
As I've stated in this Bug Report: https://github.com/JuliaLang/julialang.github.com/issues/194, given the current situation (you are violating my CR and CC-By-SA-NC 4.0 licence terms), so I cannot merge any of your PR's into `Julia.jl` while you continue to maintain `awesome-julia` as I dont want to inadvertently break the CR or CC license. After you delete `awesome-julia`, feel free to submit PR's to `Julia.jl` which I'm happy to accept. Thanks.

**Comment by melvin0008** [comment]
I have very minimal understanding of licenses. I will surely learn more about it. 
I was clearly of the thought that I can contribute to Julia.jl also since I'm the one initiating it. 

Anyway if that's how you feel , its okay.

**Comment by melvin0008** [comment]
I would also like to know what part of the entire awesome-julia do you think is plagirised?
I would be happy to delete it and put a stop to all the fuss.

**Comment by melvin0008** [comment]
My motive behind contributing to Julia.jl is for developers to get the required information, irrespective of whether they click Julia.jl or awesome-julia. 
Thanks

**Pull request closed without merging**
